Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -90,8 +90,8 @@ jobs:
           # - preset: ROCm
           #   install: https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-24.Q4-WinSvr2022-For-HIP.exe
           #   flags: '-DAMDGPU_TARGETS=gfx1010'
-          - preset: SYCL
-            install: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/e5785fb3-b5a7-4b97-89bc-918adab1f77d/intel-oneapi-base-toolkit-2025.1.3.8_offline.exe
+          # - preset: SYCL
+          #   install: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/e5785fb3-b5a7-4b97-89bc-918adab1f77d/intel-oneapi-base-toolkit-2025.1.3.8_offline.exe
     runs-on: windows
     steps:
       - run: |
@@ -179,19 +179,7 @@ jobs:
           $oneapiPath\dal\latest;` 
           $oneapiPath\compiler\latest;" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "CMPLR_ROOT=$oneapiPath\compiler\latest" | Out-File -FilePath $env:GITHUB_ENV -Append
-          echo "CPATH=$oneapiPath\tbb\latest\env\..\include;` 
-          $oneapiPath\pti\latest\env\..\include;` 
-          $oneapiPath\ocloc\latest\include;` 
-          $oneapiPath\mkl\latest\include;` 
-          $oneapiPath\ippcp\latest\include;` 
-          $oneapiPath\ipp\latest\include;` 
-          $oneapiPath\dpl\latest\include;` 
-          $oneapiPath\dpcpp-ct\latest\env\..\include;` 
-          $oneapiPath\dev-utilities\latest\include;` 
-          $oneapiPath\dal\latest\include;` 
-          $oneapiPath\dal\latest\include\dal;` 
-          $oneapiPath\compiler\latest\include;` 
-          $oneapiPath\umf\latest\include" | Out-File -FilePath $env:GITHUB_ENV -Append
+          echo "CPATH=$oneapiPath\tbb\latest\env\..\include;$oneapiPath\pti\latest\env\..\include;$oneapiPath\ocloc\latest\include;$oneapiPath\mkl\latest\include;$oneapiPath\ippcp\latest\include;$oneapiPath\ipp\latest\include;$oneapiPath\dpl\latest\include;` $oneapiPath\dpcpp-ct\latest\env\..\include;$oneapiPath\dev-utilities\latest\include;$oneapiPath\dal\latest\include;$oneapiPath\dal\latest\include\dal;$oneapiPath\compiler\latest\include;$oneapiPath\umf\latest\include" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "DALROOT=$oneapiPath\dal\latest" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "DNNLROOT=$oneapiPath\dnnl\latest\env\.." | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "DPL_ROOT=$oneapiPath\dpl\latest" | Out-File -FilePath $env:GITHUB_ENV-Append
@@ -208,13 +196,7 @@ jobs:
           echo "MKLROOT=$oneapiPath\mkl\latest" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "OCLOC_ROOT=$oneapiPath\ocloc\latest" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "ONEAPI_ROOT=$oneapiPath" | Out-File -FilePath $env:GITHUB_ENV -Append
-          echo "PKG_CONFIG_PATH=$oneapiPath\tbb\latest\lib\pkgconfig;`
-          $oneapiPath\mkl\latest\lib\pkgconfig;`
-          $oneapiPath\ippcp\latest\lib\pkgconfig;`
-          $oneapiPath\dpl\latest\lib\pkgconfig;`
-          $oneapiPath\dnnl\latest\lib\pkgconfig;`
-          $oneapiPath\dal\latest\lib\pkgconfig;`
-          $oneapiPath\compiler\latest\lib\pkgconfig" | Out-File -FilePath $env:GITHUB_ENV -Append
+          echo "PKG_CONFIG_PATH=$oneapiPath\tbb\latest\lib\pkgconfig;$oneapiPath\mkl\latest\lib\pkgconfig;$oneapiPath\ippcp\latest\lib\pkgconfig;$oneapiPath\dpl\latest\lib\pkgconfig;$oneapiPath\dnnl\latest\lib\pkgconfig;$oneapiPath\dal\latest\lib\pkgconfig;$oneapiPath\compiler\latest\lib\pkgconfig" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "PYTHONPATH=$oneapiPath\advisor\2025.1\pythonapi" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "TBBROOT=$oneapiPath\tbb\latest" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "TBB_BIN_DIR=$oneapiPath\tbb\latest\bin" | Out-File -FilePath $env:GITHUB_ENV -Append
@@ -269,89 +251,89 @@ jobs:
       - name: check that 'go mod tidy' is clean
         run: go mod tidy --diff || (echo "Please run 'go mod tidy'." && exit 1)
 
-  test:
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-    runs-on: ${{ matrix.os }}
-    env:
-      CGO_ENABLED: '1'
-      GOEXPERIMENT: 'synctest'
-    steps:
-      - name: checkout
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
+  # test:
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest, windows-latest]
+  #   runs-on: ${{ matrix.os }}
+  #   env:
+  #     CGO_ENABLED: '1'
+  #     GOEXPERIMENT: 'synctest'
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
 
-      - name: cache restore
-        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
-        with:
-          # Note: unlike the other setups, this is only grabbing the mod download
-          # cache, rather than the whole mod directory, as the download cache
-          # contains zips that can be unpacked in parallel faster than they can be
-          # fetched and extracted by tar
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod/cache
-            ~\AppData\Local\go-build
-          # NOTE: The -3- here should be incremented when the scheme of data to be
-          # cached changes (e.g. path above changes).
-          key: ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
-          restore-keys: |
-            ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-${{ hashFiles('**/go.sum') }}
-            ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-
+  #     - name: cache restore
+  #       uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
+  #       with:
+  #         # Note: unlike the other setups, this is only grabbing the mod download
+  #         # cache, rather than the whole mod directory, as the download cache
+  #         # contains zips that can be unpacked in parallel faster than they can be
+  #         # fetched and extracted by tar
+  #         path: |
+  #           ~/.cache/go-build
+  #           ~/go/pkg/mod/cache
+  #           ~\AppData\Local\go-build
+  #         # NOTE: The -3- here should be incremented when the scheme of data to be
+  #         # cached changes (e.g. path above changes).
+  #         key: ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
+  #         restore-keys: |
+  #           ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-${{ hashFiles('**/go.sum') }}
+  #           ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-
 
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          # The caching strategy of setup-go is less than ideal, and wastes
-          # time by not saving artifacts due to small failures like the linter
-          # complaining, etc. This means subsequent have to rebuild their world
-          # again until all checks pass. For instance, if you mispell a word,
-          # you're punished until you fix it. This is more hostile than
-          # helpful.
-          cache: false
+  #     - name: Setup Go
+  #       uses: actions/setup-go@v5
+  #       with:
+  #         # The caching strategy of setup-go is less than ideal, and wastes
+  #         # time by not saving artifacts due to small failures like the linter
+  #         # complaining, etc. This means subsequent have to rebuild their world
+  #         # again until all checks pass. For instance, if you mispell a word,
+  #         # you're punished until you fix it. This is more hostile than
+  #         # helpful.
+  #         cache: false
 
-          go-version-file: go.mod
+  #         go-version-file: go.mod
 
-      # It is tempting to run this in a platform independent way, but the past
-      # shows this codebase will see introductions of platform specific code
-      # generation, and so we need to check this per platform to ensure we
-      # don't abuse go generate on specific platforms.
-      - name: check that 'go generate' is clean
-        if: always()
-        run: |
-          go generate ./...
-          git diff --name-only --exit-code || (echo "Please run 'go generate ./...'." && exit 1)
+  #     # It is tempting to run this in a platform independent way, but the past
+  #     # shows this codebase will see introductions of platform specific code
+  #     # generation, and so we need to check this per platform to ensure we
+  #     # don't abuse go generate on specific platforms.
+  #     - name: check that 'go generate' is clean
+  #       if: always()
+  #       run: |
+  #         go generate ./...
+  #         git diff --name-only --exit-code || (echo "Please run 'go generate ./...'." && exit 1)
 
-      - name: go test
-        if: always()
-        run: go test -count=1 -benchtime=1x ./...
+  #     - name: go test
+  #       if: always()
+  #       run: go test -count=1 -benchtime=1x ./...
 
-      # TODO(bmizerany): replace this heavy tool with just the
-      # tools/checks/binaries we want and then make them all run in parallel
-      # across jobs, not on a single tiny vm on Github Actions.
-      - uses: golangci/golangci-lint-action@v6
-        with:
-          args: --timeout 10m0s -v
+  #     # TODO(bmizerany): replace this heavy tool with just the
+  #     # tools/checks/binaries we want and then make them all run in parallel
+  #     # across jobs, not on a single tiny vm on Github Actions.
+  #     - uses: golangci/golangci-lint-action@v6
+  #       with:
+  #         args: --timeout 10m0s -v
 
-      - name: cache save
-        # Always save the cache, even if the job fails. The artifacts produced
-        # during the building of test binaries are not all for naught. They can
-        # be used to speed up subsequent runs.
-        if: always()
+  #     - name: cache save
+  #       # Always save the cache, even if the job fails. The artifacts produced
+  #       # during the building of test binaries are not all for naught. They can
+  #       # be used to speed up subsequent runs.
+  #       if: always()
 
-        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
-        with:
-          # Note: unlike the other setups, this is only grabbing the mod download
-          # cache, rather than the whole mod directory, as the download cache
-          # contains zips that can be unpacked in parallel faster than they can be
-          # fetched and extracted by tar
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod/cache
-            ~\AppData\Local\go-build
-          # NOTE: The -3- here should be incremented when the scheme of data to be
-          # cached changes (e.g. path above changes).
-          key: ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
+  #       uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
+  #       with:
+  #         # Note: unlike the other setups, this is only grabbing the mod download
+  #         # cache, rather than the whole mod directory, as the download cache
+  #         # contains zips that can be unpacked in parallel faster than they can be
+  #         # fetched and extracted by tar
+  #         path: |
+  #           ~/.cache/go-build
+  #           ~/go/pkg/mod/cache
+  #           ~\AppData\Local\go-build
+  #         # NOTE: The -3- here should be incremented when the scheme of data to be
+  #         # cached changes (e.g. path above changes).
+  #         key: ${{ github.job }}-${{ runner.os }}-${{ matrix.goarch }}-${{ matrix.buildflags }}-go-3-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
 
   patches:
     runs-on: ubuntu-latest
